//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fodler.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class FodlerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static FodlerSettings defaultInstance = ((FodlerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FodlerSettings())));
        
        public static FodlerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool waitForSync {
            get {
                return ((bool)(this["waitForSync"]));
            }
            set {
                this["waitForSync"] = value;
            }
        }
    }
}
