//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fodler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyAddin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze stared.
        /// </summary>
        public static string AnalyzeStared {
            get {
                return ResourceManager.GetString("AnalyzeStared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing.
        /// </summary>
        public static string Analyzing {
            get {
                return ResourceManager.GetString("Analyzing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent, thank you..
        /// </summary>
        public static string EmailSentThankYou {
            get {
                return ResourceManager.GetString("EmailSentThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred: .
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fodler error report.
        /// </summary>
        public static string FodlerErrorReport {
            get {
                return ResourceManager.GetString("FodlerErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap iconChoose {
            get {
                object obj = ResourceManager.GetObject("iconChoose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap iconMove {
            get {
                object obj = ResourceManager.GetObject("iconMove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap iconMoveAll {
            get {
                object obj = ResourceManager.GetObject("iconMoveAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap iconOptions {
            get {
                object obj = ResourceManager.GetObject("iconOptions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap iconRevert {
            get {
                object obj = ResourceManager.GetObject("iconRevert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiclass.
        /// </summary>
        public static string Multiclass {
            get {
                return ResourceManager.GetString("Multiclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NaiveBayes.
        /// </summary>
        public static string NaiveBayes {
            get {
                return ResourceManager.GetString("NaiveBayes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving data.
        /// </summary>
        public static string SavingData {
            get {
                return ResourceManager.GetString("SavingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder first.
        /// </summary>
        public static string SelectFolderFirst {
            get {
                return ResourceManager.GetString("SelectFolderFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a parent folder first.
        /// </summary>
        public static string SelectParentFirst {
            get {
                return ResourceManager.GetString("SelectParentFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ačkoli
        ///ahoj
        ///ale
        ///anebo
        ///ano
        ///asi
        ///aspoň
        ///během
        ///bez
        ///beze
        ///blízko
        ///bohužel
        ///brzo
        ///bude
        ///budeme
        ///budeš
        ///budete
        ///budou
        ///budu
        ///byl
        ///byla
        ///byli
        ///bylo
        ///byly
        ///bys
        ///čau
        ///chce
        ///chceme
        ///chceš
        ///chcete
        ///chci
        ///chtějí
        ///chtít
        ///chut&apos;
        ///chuti
        ///co
        ///čtrnáct
        ///čtyři
        ///dál
        ///dále
        ///daleko
        ///děkovat
        ///děkujeme
        ///děkuji
        ///den
        ///deset
        ///devatenáct
        ///devět
        ///do
        ///dobrý
        ///docela
        ///dva
        ///dvacet
        ///dvanáct
        ///dvě
        ///hodně
        ///já
        ///jak
        ///jde
        ///je
        ///jeden
        ///jedenáct
        ///jedna
        ///jedno
        ///jednou
        ///jedou
        ///jeho
        ///její
        ///jejich
        ///jemu
        ///jen
        ///jenom
        ///ještě
        ///jestli
        ///jestliže
        ///jí
        ///ji [rest of string was truncated]&quot;;.
        /// </summary>
        public static string stopwords_cz {
            get {
                return ResourceManager.GetString("stopwords_cz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///a&apos;s
        ///able
        ///about
        ///above
        ///according
        ///accordingly
        ///across
        ///actually
        ///after
        ///afterwards
        ///again
        ///against
        ///ain&apos;t
        ///all
        ///allow
        ///allows
        ///almost
        ///alone
        ///along
        ///already
        ///also
        ///although
        ///always
        ///am
        ///among
        ///amongst
        ///an
        ///and
        ///another
        ///any
        ///anybody
        ///anyhow
        ///anyone
        ///anything
        ///anyway
        ///anyways
        ///anywhere
        ///apart
        ///appear
        ///appreciate
        ///appropriate
        ///are
        ///aren&apos;t
        ///around
        ///as
        ///aside
        ///ask
        ///asking
        ///associated
        ///at
        ///available
        ///away
        ///awfully
        ///b
        ///be
        ///became
        ///because
        ///become
        ///becomes
        ///becoming
        ///been
        ///before
        ///beforehand
        ///behind
        ///being
        ///b [rest of string was truncated]&quot;;.
        /// </summary>
        public static string stopwords_en {
            get {
                return ResourceManager.GetString("stopwords_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a,aby,aj,ako,aký,ale,alebo,ani,avšak,ba,bez,buï,cez,do,ho,hoci,i,ich,im,ja,jeho,jej,jemu,ju,k,kam,kde,kedže,keï,kto,ktorý,ku,lebo,ma,mi,mne,mnou,mu,my,mòa,môj,na,nad,nami,neho,nej,nemu,nich,nielen,nim,no,nám,nás,náš,ním,o,od,on,ona,oni,ono,ony,po,pod,pre,pred,pri,s,sa,seba,sem,so,svoj,taký,tam,teba,tebe,tebou,tej,ten,ti,tie,to,toho,tomu,tou,tvoj,ty,tá,tým,v,vami,veï,vo,vy,vám,vás,váš,však,z,za,zo,a,èi,èo,èí,òom,òou,òu,že.
        /// </summary>
        public static string stopwords_sk {
            get {
                return ResourceManager.GetString("stopwords_sk", resourceCulture);
            }
        }
    }
}
